"""init

Revision ID: 74bd626c4016
Revises: 4a5de975d2b6
Create Date: 2017-07-01 20:07:39.590974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74bd626c4016'
down_revision = '4a5de975d2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('wootowa_devices_push_token2_key', 'wootowa_devices', type_='unique')
    op.drop_column('wootowa_devices', 'push_token2')
    op.drop_column('wootowa_users', 'age2')
    op.drop_column('wootowa_users', 'age3')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wootowa_users', sa.Column('age3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wootowa_users', sa.Column('age2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('wootowa_devices', sa.Column('push_token2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('wootowa_devices_push_token2_key', 'wootowa_devices', ['push_token2'])
    # ### end Alembic commands ###
