"""add social user

Revision ID: bf647a649477
Revises: 74bd626c4016
Create Date: 2017-07-01 21:18:00.894732

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf647a649477'
down_revision = '74bd626c4016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wootowa_devices')
    op.add_column('wootowa_users', sa.Column('social_user_id', sa.Integer(), nullable=False))
    op.alter_column('wootowa_users', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wootowa_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('wootowa_users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=False)
    op.alter_column('wootowa_users', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('wootowa_users_social_id_key', 'wootowa_users', type_='unique')
    op.create_unique_constraint(None, 'wootowa_users', ['social_user_id'])
    op.create_foreign_key(None, 'wootowa_users', 'wootowa_socials', ['social_user_id'], ['id'])
    op.drop_column('wootowa_users', 'social_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wootowa_users', sa.Column('social_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'wootowa_users', type_='foreignkey')
    op.drop_constraint(None, 'wootowa_users', type_='unique')
    op.create_unique_constraint('wootowa_users_social_id_key', 'wootowa_users', ['social_id'])
    op.alter_column('wootowa_users', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('wootowa_users', 'gender',
               existing_type=postgresql.ENUM('male', 'female', name='gender'),
               nullable=True)
    op.alter_column('wootowa_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('wootowa_users', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('wootowa_users', 'social_user_id')
    op.create_table('wootowa_devices',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('push_token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wootowa_devices_pkey'),
    sa.UniqueConstraint('push_token', name='wootowa_devices_push_token_key')
    )
    # ### end Alembic commands ###
